#!/bin/sh
NAME=koha-sip
PERL5LIB=/home/koha/kohaclone
KOHA_CONF=/home/koha/koha-dev/etc/koha-conf.xml
SIPCTL=/home/koha/koha-dev/bin/sipctl
export PERL5LIB KOHA_CONF


case "$1" in
    start)
      echo "Starting Sip Server"
      $SIPCTL start
      ;;
    stop)
      echo "Stopping Sip Server"
      $SIPCTL stop
      ;;
    restart)
      echo "Restarting the Zebra Server"
      $SIPCTL restart
      ;;
    *)
      echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
      exit 1
      ;;
esac

