#!/usr/bin/perl
use strict;
use warnings;

my $cmd = shift;

my @params = @ARGV;


my %function = (
    start => \&start_listener,
    stop => \&stop_listener,
    restart => \&restart_listener,
);

if ( !exists $function{$cmd}) {
    print STDERR "Unrecognised command\n";
    exit(1);
}

my $port;

if (@params) {

}

my $program = 'sipserver.pl';
my $piddir = '/home/koha/koha-dev/var/run';
my $bindir='/home/koha/kohaclone/C4/SIP';
my $config_dir='/home/koha/kohaclone/C4/SIP';
my $server = join q{/}, $bindir, $program;
my $pidfile = join q{/}, $piddir, 'sipserver.pid';
my $server_pid;
my $config_file = join q{/}, $config_dir, 'SIPTESTconfig.xml';

if ($cmd ne 'start' ) {
    open my $fh, '<', $pidfile or die "Cannot read pid from $pidfile : $!";
    my $line = <$fh>;
    close $fh;
    if ($line=~m/(\d+)/) {
        $server_pid = $1;
    }
    else {
        die "no pid found for server";
    }
}

&{$function{$cmd}}();



sub start_listener {
    exec($server, $config_file) or print STDERR "Could not start $server for $config_file : $!";
    return;
}

sub stop_listener {
    kill 'SIGQUIT', $server_pid;
}

sub restart_listener {
    kill 'SIGHUP', $server_pid;
}
