#!/bin/sh
### BEGIN INIT INFO
# Provides:          sipserver
# Required-Start:    $local_fs $remote_fs $syslog $network $time
# Required-Stop:     $local_fs $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Sipserver interface to koha.
### END INIT INFO

SIPCTL=/home/koha/koha-dev/bin/sipctl
export PERL5LIB KOHA_CONF


case "$1" in
    start)
      echo "Starting Sip Server"
      $SIPCTL start
      ;;
    stop)
      echo "Stopping Sip Server"
      $SIPCTL stop
      ;;
    restart)
      echo "Restarting the Sip Server"
      $SIPCTL restart
      ;;
    force-reload)
      echo "Reloading the Sip Server"
      $SIPCTL stop
      $SIPCTL start
      ;;
    *)
      echo "Usage: $0 {start|stop|restart|force-reload}"
      exit 1
      ;;
esac

exit 0
